"""modele feu tricolore créé et mise à jour des champs des autres modèles

Revision ID: 45adfef884e4
Revises: 735c01c10a0c
Create Date: 2025-05-18 22:03:23.701228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45adfef884e4'
down_revision: Union[str, None] = '735c01c10a0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
