"""Mise à jour modèle feu tricolore et carrefour

Revision ID: 59991ebe6a0d
Revises: 45adfef884e4
Create Date: 2025-05-19 13:59:24.342335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59991ebe6a0d'
down_revision: Union[str, None] = '45adfef884e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
